version: '3.4'

services:
  wefox-node:
    image: wefox-node
    container_name: nodeApp
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app
    links: 
      - mongodb
  redis: 
    image: redis:latest
    container_name: redis
    ports: 
      - 6379:6379
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: