version: '3'

services:

    mongo:
      image: mongo:4.0.0
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
  
    mongo-express:
      image: mongo-express
      restart: always
      volumes: 
        - ./data:/data/db
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
    
    
    redis-cache:
        image: redis:5.0.5
        restart: always
        volumes: 
            - ./data:/data/cache
        ports:
            - "6379:6379"
    
    node-server:
        image: "node:12.7.0"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        ports:
            - 8080:8080
        restart: always
        environment:
            - NODE_ENV=development
        command: "npm start"
